# -*- coding: utf-8 -*-
"""predictDiseaseImage.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z4_biW4NeO1KcMz7PGEbJsiCFw8hBoaS
"""

# -*- coding: utf-8 -*-
"""optimized_dermatology_model.ipynb

Optimized version with improved techniques for better accuracy
"""

from google.colab import drive
drive.mount('/content/drive')

# Install required packages
!pip install timm -q
!pip install scikit-learn -q
!pip install albumentations -q

# Import libraries
import os
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader, WeightedRandomSampler
from torchvision import transforms
from PIL import Image
import pandas as pd
import numpy as np
import timm
from sklearn.utils.class_weight import compute_class_weight
from sklearn.metrics import accuracy_score, precision_recall_fscore_support, classification_report, confusion_matrix, roc_auc_score
from sklearn.preprocessing import label_binarize
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm.auto import tqdm
import warnings
import albumentations as A
from albumentations.pytorch import ToTensorV2
warnings.filterwarnings('ignore')

# Set random seeds for reproducibility
torch.manual_seed(42)
np.random.seed(42)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(42)

# Device setup
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")
if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)}")

DRIVE_BASE = "/content/drive/MyDrive/ThangNQ-NamBH/resource3kdata"
TRAIN_CSV = os.path.join(DRIVE_BASE, "train.csv")
IMG_DIR = os.path.join(DRIVE_BASE, "skin_diseases_data")

# Hyperparameters - OPTIMIZED
BATCH_SIZE = 32  # Increased for better gradient estimates
NUM_EPOCHS = 50  # More epochs with early stopping
LEARNING_RATE = 0.0005  # Slightly higher initial LR
WEIGHT_DECAY = 1e-4
IMG_SIZE = 256  # Increased resolution for better feature extraction
NUM_WORKERS = 0  # For faster data loading

# Split ratios
TRAIN_RATIO = 0.8
VAL_RATIO = 0.1
TEST_RATIO = 0.1

print(f"Configuration:")
print(f"- Batch Size: {BATCH_SIZE}")
print(f"- Epochs: {NUM_EPOCHS}")
print(f"- Learning Rate: {LEARNING_RATE}")
print(f"- Image Size: {IMG_SIZE}x{IMG_SIZE}")

print("\n" + "="*50)
print("DATA PREPROCESSING")
print("="*50)

# Load and clean data
df = pd.read_csv(TRAIN_CSV)
print(f"Original dataset size: {len(df)}")

# Remove low quality images
if 'qc' in df.columns:
    before_count = len(df)
    mask_contains_3 = df['qc'].astype(str).str.strip().str.contains('3', na=False)
    df = df[~mask_contains_3]
    print(f"Đã xóa các hàng có cột 'qc' chứa ký tự '3'")
    print(f"Số hàng trước: {before_count}")
    print(f"Số hàng sau: {len(df)}")

print("\nLabel distribution:")
print(df['label'].value_counts())

# Create label mapping
unique_labels = sorted(df['label'].unique())
label_to_idx = {label: idx for idx, label in enumerate(unique_labels)}
idx_to_label = {idx: label for label, idx in label_to_idx.items()}
num_classes = len(unique_labels)

print(f"\nNumber of classes: {num_classes}")
df['label_encoded'] = df['label'].map(label_to_idx)

# Split dataset
from sklearn.model_selection import train_test_split

train_df, temp_df = train_test_split(
    df, test_size=(VAL_RATIO + TEST_RATIO),
    stratify=df['label_encoded'],
    random_state=42
)

val_df, test_df = train_test_split(
    temp_df, test_size=TEST_RATIO/(VAL_RATIO + TEST_RATIO),
    stratify=temp_df['label_encoded'],
    random_state=42
)

print(f"\nDataset split:")
print(f"- Train: {len(train_df)} samples")
print(f"- Validation: {len(val_df)} samples")
print(f"- Test: {len(test_df)} samples")

print("\n" + "="*50)
print("ADVANCED DATA AUGMENTATION SETUP")
print("="*50)

# OPTIMIZATION 1: Advanced Augmentation with Albumentations
train_transform_albu = A.Compose([
    A.Resize(IMG_SIZE, IMG_SIZE),
    A.HorizontalFlip(p=0.5),
    A.VerticalFlip(p=0.3),
    A.RandomRotate90(p=0.3),
    A.ShiftScaleRotate(shift_limit=0.1, scale_limit=0.2, rotate_limit=30, p=0.5),
    A.OneOf([
        A.GaussNoise(var_limit=(10.0, 50.0)),
        A.GaussianBlur(blur_limit=(3, 7)),
        A.MotionBlur(blur_limit=5),
    ], p=0.3),
    A.OneOf([
        A.OpticalDistortion(distort_limit=0.2),
        A.GridDistortion(num_steps=5, distort_limit=0.2),
    ], p=0.2),
    A.ColorJitter(brightness=0.3, contrast=0.3, saturation=0.3, hue=0.15, p=0.5),
    A.RandomBrightnessContrast(brightness_limit=0.2, contrast_limit=0.2, p=0.5),
    A.CLAHE(clip_limit=2.0, p=0.3),
    A.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
    ToTensorV2()
])

val_transform_albu = A.Compose([
    A.Resize(IMG_SIZE, IMG_SIZE),
    A.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
    ToTensorV2()
])

print("Advanced augmentation techniques applied:")
print("- Geometric: Horizontal/Vertical Flip, Rotate90, ShiftScaleRotate")
print("- Noise: GaussNoise, GaussianBlur, MotionBlur")
print("- Distortion: OpticalDistortion, GridDistortion")
print("- Color: ColorJitter, RandomBrightnessContrast, CLAHE")

# Custom Dataset with Albumentations
class SkinDiseaseDataset(Dataset):
    def __init__(self, dataframe, img_dir, transform=None):
        self.data = dataframe.reset_index(drop=True)
        self.img_dir = img_dir
        self.transform = transform

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        row = self.data.iloc[idx]
        img_name = row['md5hash'] + ".jpg"
        label_folder = row['label']
        img_path = os.path.join(self.img_dir, label_folder, img_name)

        try:
            image = Image.open(img_path).convert('RGB')
            image = np.array(image)
        except Exception as e:
            print(f"Error loading image {img_path}: {e}")
            image = np.zeros((IMG_SIZE, IMG_SIZE, 3), dtype=np.uint8)

        if self.transform:
            augmented = self.transform(image=image)
            image = augmented['image']

        label = torch.tensor(row['label_encoded'], dtype=torch.long)
        return image, label

# Create datasets
train_dataset = SkinDiseaseDataset(train_df, IMG_DIR, transform=train_transform_albu)
val_dataset = SkinDiseaseDataset(val_df, IMG_DIR, transform=val_transform_albu)
test_dataset = SkinDiseaseDataset(test_df, IMG_DIR, transform=val_transform_albu)

print(f"\nDatasets created successfully")

print("\n" + "="*50)
print("HANDLING CLASS IMBALANCE")
print("="*50)

# Compute class weights
labels = train_df['label_encoded'].values
class_weights = compute_class_weight('balanced', classes=np.unique(labels), y=labels)
class_weights_tensor = torch.tensor(class_weights, dtype=torch.float).to(device)

print("Class weights:")
for label, weight in zip(unique_labels, class_weights):
    print(f"  {label}: {weight:.4f}")

# Create weighted sampler
sample_weights = np.array([class_weights[label] for label in labels])
sampler = WeightedRandomSampler(
    weights=sample_weights,
    num_samples=len(sample_weights),
    replacement=True
)

# Create data loaders
train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, sampler=sampler,
                          num_workers=NUM_WORKERS, pin_memory=True, persistent_workers=True if NUM_WORKERS > 0 else False)
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False,
                        num_workers=NUM_WORKERS, pin_memory=True, persistent_workers=True if NUM_WORKERS > 0 else False)
test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False,
                         num_workers=NUM_WORKERS, pin_memory=True, persistent_workers=True if NUM_WORKERS > 0 else False)

print(f"\nData loaders created with batch size: {BATCH_SIZE}")

print("\n" + "="*50)
print("BUILDING OPTIMIZED FUSION MODEL")
print("="*50)

# OPTIMIZATION 2: Improved Fusion Model with Attention Mechanism
class AttentionFusion(nn.Module):
    """Attention mechanism for feature fusion"""
    def __init__(self, num_features):
        super(AttentionFusion, self).__init__()
        self.attention = nn.Sequential(
            nn.Linear(num_features, num_features // 4),
            nn.ReLU(),
            nn.Linear(num_features // 4, num_features),
            nn.Sigmoid()
        )

    def forward(self, x):
        attention_weights = self.attention(x)
        return x * attention_weights

class ImprovedFusionModel(nn.Module):
    """
    Enhanced Fusion model with:
    - Fine-tuning of all layers
    - Attention mechanism
    - Batch Normalization
    - Improved classifier architecture
    """
    def __init__(self, num_classes):
        super(ImprovedFusionModel, self).__init__()

        # Load pre-trained models
        self.efficientnet_b0 = timm.create_model('efficientnet_b0', pretrained=True)
        self.efficientnet_b2 = timm.create_model('efficientnet_b2', pretrained=True)
        self.resnet50 = timm.create_model('resnet50', pretrained=True)

        # Get feature dimensions
        self.b0_features = self.efficientnet_b0.num_features
        self.b2_features = self.efficientnet_b2.num_features
        self.resnet_features = self.resnet50.num_features

        # Remove classification heads
        self.efficientnet_b0.classifier = nn.Identity()
        self.efficientnet_b2.classifier = nn.Identity()
        self.resnet50.fc = nn.Identity()

        # Total fused features
        self.total_features = self.b0_features + self.b2_features + self.resnet_features

        # OPTIMIZATION: Add attention mechanism
        self.attention = AttentionFusion(self.total_features)

        # OPTIMIZATION: Improved classifier with BatchNorm and residual connections
        self.bn1 = nn.BatchNorm1d(self.total_features)

        self.classifier = nn.Sequential(
            nn.Linear(self.total_features, 1024),
            nn.BatchNorm1d(1024),
            nn.ReLU(),
            nn.Dropout(0.5),

            nn.Linear(1024, 512),
            nn.BatchNorm1d(512),
            nn.ReLU(),
            nn.Dropout(0.4),

            nn.Linear(512, 256),
            nn.BatchNorm1d(256),
            nn.ReLU(),
            nn.Dropout(0.3),

            nn.Linear(256, num_classes)
        )

    def forward(self, x):
        # Extract features from each model
        feat_b0 = self.efficientnet_b0(x)
        feat_b2 = self.efficientnet_b2(x)
        feat_resnet = self.resnet50(x)

        # Concatenate features (fusion)
        fused_features = torch.cat([feat_b0, feat_b2, feat_resnet], dim=1)

        # Apply batch normalization
        fused_features = self.bn1(fused_features)

        # Apply attention mechanism
        fused_features = self.attention(fused_features)

        # Classification
        output = self.classifier(fused_features)

        return output

# Initialize model
model = ImprovedFusionModel(num_classes=num_classes)
model = model.to(device)

print("Improved Fusion Model Architecture:")
print(f"- EfficientNet-B0 features: {model.b0_features}")
print(f"- EfficientNet-B2 features: {model.b2_features}")
print(f"- ResNet50 features: {model.resnet_features}")
print(f"- Total fused features: {model.total_features}")
print(f"- Attention mechanism: ✓")
print(f"- Classification layers: 1024 -> 512 -> 256 -> {num_classes}")

# Count parameters
total_params = sum(p.numel() for p in model.parameters())
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"\nTotal parameters: {total_params:,}")
print(f"Trainable parameters: {trainable_params:,}")

print("\n" + "="*50)
print("OPTIMIZED TRAINING SETUP")
print("="*50)

# OPTIMIZATION 3: Label Smoothing for better generalization
class LabelSmoothingCrossEntropy(nn.Module):
    def __init__(self, epsilon=0.1, weight=None):
        super(LabelSmoothingCrossEntropy, self).__init__()
        self.epsilon = epsilon
        self.weight = weight

    def forward(self, outputs, targets):
        n_classes = outputs.size(-1)
        log_probs = torch.nn.functional.log_softmax(outputs, dim=-1)

        # One-hot encoding with label smoothing
        targets_one_hot = torch.zeros_like(log_probs).scatter_(1, targets.unsqueeze(1), 1)
        targets_smooth = targets_one_hot * (1 - self.epsilon) + self.epsilon / n_classes

        loss = -(targets_smooth * log_probs).sum(dim=-1)

        if self.weight is not None:
            loss = loss * self.weight[targets]

        return loss.mean()

# Loss function with label smoothing
criterion = LabelSmoothingCrossEntropy(epsilon=0.1, weight=class_weights_tensor)

# OPTIMIZATION 4: Separate learning rates for different parts
backbone_params = []
classifier_params = []

for name, param in model.named_parameters():
    if 'classifier' in name or 'attention' in name or 'bn1' in name:
        classifier_params.append(param)
    else:
        backbone_params.append(param)

optimizer = optim.AdamW([
    {'params': backbone_params, 'lr': LEARNING_RATE * 0.1},  # Lower LR for pretrained backbones
    {'params': classifier_params, 'lr': LEARNING_RATE}       # Higher LR for new layers
], weight_decay=WEIGHT_DECAY)

# OPTIMIZATION 5: Cosine Annealing with Warm Restarts
scheduler = optim.lr_scheduler.CosineAnnealingWarmRestarts(
    optimizer, T_0=10, T_mult=2, eta_min=1e-6
)

print(f"Loss: Label Smoothing CrossEntropyLoss (ε=0.1) with class weights")
print(f"Optimizer: AdamW with differential learning rates")
print(f"  - Backbone LR: {LEARNING_RATE * 0.1}")
print(f"  - Classifier LR: {LEARNING_RATE}")
print(f"Scheduler: CosineAnnealingWarmRestarts (T_0=10, T_mult=2)")

# OPTIMIZATION 6: Mixed Precision Training
scaler = torch.cuda.amp.GradScaler() if torch.cuda.is_available() else None
print(f"Mixed Precision Training: {'Enabled' if scaler else 'Disabled'}")

# OPTIMIZATION 7: Gradient Clipping
MAX_GRAD_NORM = 1.0

def train_epoch(model, loader, criterion, optimizer, device, scaler=None):
    model.train()
    running_loss = 0.0
    correct = 0
    total = 0

    pbar = tqdm(loader, desc="Training")
    for images, labels in pbar:
        images, labels = images.to(device), labels.to(device)

        optimizer.zero_grad()

        # Mixed precision training
        if scaler:
            with torch.cuda.amp.autocast():
                outputs = model(images)
                loss = criterion(outputs, labels)

            scaler.scale(loss).backward()
            scaler.unscale_(optimizer)
            torch.nn.utils.clip_grad_norm_(model.parameters(), MAX_GRAD_NORM)
            scaler.step(optimizer)
            scaler.update()
        else:
            outputs = model(images)
            loss = criterion(outputs, labels)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), MAX_GRAD_NORM)
            optimizer.step()

        running_loss += loss.item()
        _, predicted = torch.max(outputs, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

        pbar.set_postfix({'loss': f'{loss.item():.4f}'})

    epoch_loss = running_loss / len(loader)
    epoch_acc = 100 * correct / total
    return epoch_loss, epoch_acc

def validate_epoch(model, loader, criterion, device):
    model.eval()
    running_loss = 0.0
    correct = 0
    total = 0

    with torch.no_grad():
        for images, labels in tqdm(loader, desc="Validation"):
            images, labels = images.to(device), labels.to(device)

            if torch.cuda.is_available():
                with torch.cuda.amp.autocast():
                    outputs = model(images)
                    loss = criterion(outputs, labels)
            else:
                outputs = model(images)
                loss = criterion(outputs, labels)

            running_loss += loss.item()
            _, predicted = torch.max(outputs, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

    epoch_loss = running_loss / len(loader)
    epoch_acc = 100 * correct / total
    return epoch_loss, epoch_acc

print("\n" + "="*50)
print("STARTING TRAINING")
print("="*50)

# Training history
history = {
    'train_loss': [], 'train_acc': [],
    'val_loss': [], 'val_acc': [],
    'lr': []
}

best_val_acc = 0.0
best_model_path = 'best_optimized_model.pth'
patience_counter = 0
PATIENCE = 15  # Early stopping patience

for epoch in range(NUM_EPOCHS):
    print(f"\nEpoch {epoch+1}/{NUM_EPOCHS}")
    print("-" * 50)

    # Train
    train_loss, train_acc = train_epoch(model, train_loader, criterion, optimizer, device, scaler)

    # Validate
    val_loss, val_acc = validate_epoch(model, val_loader, criterion, device)

    # Update scheduler
    scheduler.step()

    # Save history
    history['train_loss'].append(train_loss)
    history['train_acc'].append(train_acc)
    history['val_loss'].append(val_loss)
    history['val_acc'].append(val_acc)
    history['lr'].append(optimizer.param_groups[0]['lr'])

    # Print results
    print(f"Train Loss: {train_loss:.4f}, Train Acc: {train_acc:.2f}%")
    print(f"Val Loss: {val_loss:.4f}, Val Acc: {val_acc:.2f}%")
    print(f"Learning Rate: {optimizer.param_groups[0]['lr']:.6f}")

    # Save best model
    if val_acc > best_val_acc:
        best_val_acc = val_acc
        torch.save(model.state_dict(), best_model_path)
        print(f"✓ Best model saved with val_acc: {val_acc:.2f}%")
        patience_counter = 0
    else:
        patience_counter += 1
        if patience_counter >= PATIENCE:
            print(f"\nEarly stopping triggered after {epoch+1} epochs")
            break

print("\n" + "="*50)
print("TRAINING COMPLETED")
print("="*50)
print(f"Best Validation Accuracy: {best_val_acc:.2f}%")

# Plot training history
print("\n" + "="*50)
print("TRAINING VISUALIZATION")
print("="*50)

fig, axes = plt.subplots(1, 3, figsize=(20, 5))

# Loss plot
axes[0].plot(history['train_loss'], label='Train Loss', marker='o')
axes[0].plot(history['val_loss'], label='Val Loss', marker='s')
axes[0].set_xlabel('Epoch')
axes[0].set_ylabel('Loss')
axes[0].set_title('Training and Validation Loss')
axes[0].legend()
axes[0].grid(True)

# Accuracy plot
axes[1].plot(history['train_acc'], label='Train Acc', marker='o')
axes[1].plot(history['val_acc'], label='Val Acc', marker='s')
axes[1].set_xlabel('Epoch')
axes[1].set_ylabel('Accuracy (%)')
axes[1].set_title('Training and Validation Accuracy')
axes[1].legend()
axes[1].grid(True)

# Learning rate plot
axes[2].plot(history['lr'], label='Learning Rate', marker='o', color='green')
axes[2].set_xlabel('Epoch')
axes[2].set_ylabel('Learning Rate')
axes[2].set_title('Learning Rate Schedule')
axes[2].set_yscale('log')
axes[2].legend()
axes[2].grid(True)

plt.tight_layout()
plt.savefig('training_history_optimized.png', dpi=300, bbox_inches='tight')
plt.show()

print("Training history plots saved as 'training_history_optimized.png'")

# Evaluation on test set
print("\n" + "="*50)
print("EVALUATION ON TEST SET")
print("="*50)

model.load_state_dict(torch.load(best_model_path))
model.eval()

all_preds = []
all_labels = []
all_probs = []

with torch.no_grad():
    for images, labels in tqdm(test_loader, desc="Testing"):
        images, labels = images.to(device), labels.to(device)

        if torch.cuda.is_available():
            with torch.cuda.amp.autocast():
                outputs = model(images)
        else:
            outputs = model(images)

        probs = torch.softmax(outputs, dim=1)
        _, predicted = torch.max(outputs, 1)

        all_preds.extend(predicted.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())
        all_probs.extend(probs.cpu().numpy())

all_preds = np.array(all_preds)
all_labels = np.array(all_labels)
all_probs = np.array(all_probs)

# Calculate metrics
test_accuracy = accuracy_score(all_labels, all_preds)
precision, recall, f1, _ = precision_recall_fscore_support(
    all_labels, all_preds, average='weighted', zero_division=0
)

print(f"\nTest Set Performance:")
print(f"- Accuracy: {test_accuracy*100:.2f}%")
print(f"- Precision: {precision:.4f}")
print(f"- Recall: {recall:.4f}")
print(f"- F1-Score: {f1:.4f}")

print("\nDetailed Classification Report:")
print(classification_report(
    all_labels, all_preds,
    target_names=unique_labels,
    zero_division=0
))

# Confusion Matrix
cm = confusion_matrix(all_labels, all_preds)

plt.figure(figsize=(12, 10))
sns.heatmap(
    cm, annot=True, fmt='d', cmap='Blues',
    xticklabels=unique_labels,
    yticklabels=unique_labels
)
plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('Confusion Matrix - Optimized Model')
plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)
plt.tight_layout()
plt.savefig('confusion_matrix_optimized.png', dpi=300, bbox_inches='tight')
plt.show()

# Save final model
final_model_path = 'skin_disease_optimized_final.pth'
torch.save({
    'model_state_dict': model.state_dict(),
    'label_mapping': label_to_idx,
    'idx_to_label': idx_to_label,
    'num_classes': num_classes,
    'best_val_acc': best_val_acc,
    'test_accuracy': test_accuracy,
    'history': history
}, final_model_path)

print(f"\n✓ Model saved to: {final_model_path}")
print(f"✓ Best validation accuracy: {best_val_acc:.2f}%")
print(f"✓ Test accuracy: {test_accuracy*100:.2f}%")

# Save to Drive
import shutil
drive_save_path = os.path.join(DRIVE_BASE, "models_optimized")
os.makedirs(drive_save_path, exist_ok=True)
shutil.copy(final_model_path, os.path.join(drive_save_path, final_model_path))
shutil.copy('training_history_optimized.png', os.path.join(drive_save_path, 'training_history_optimized.png'))
shutil.copy('confusion_matrix_optimized.png', os.path.join(drive_save_path, 'confusion_matrix_optimized.png'))

print(f"\n✓ All files backed up to Google Drive: {drive_save_path}")
print("\n" + "="*50)
print("OPTIMIZED TRAINING PIPELINE COMPLETED!")
print("="*50)